bsdinstall: add support for graphical mode
Just like for bsdconfig(8), this allows bsdinstall(8) to be started with
the -X command-line parameter, thereby defaulting to Xdialog(1) in stead
of bsddialog(1) to render the user interface.

With this patch, the same is also true for startbsdinstall, which in
turn will start bsdinstall(8) with the -X parameter when called itself
with -X.

Sponsored by:	The FreeBSD Foundation

diff --git a/usr.sbin/bsdinstall/scripts/auto b/usr.sbin/bsdinstall/scripts/auto
--- a/usr.sbin/bsdinstall/scripts/auto
+++ b/usr.sbin/bsdinstall/scripts/auto
@@ -32,6 +32,9 @@ BSDCFG_SHARE="/usr/share/bsdconfig"
 . $BSDCFG_SHARE/common.subr || exit 1
 f_include $BSDCFG_SHARE/dialog.subr
 
+: ${DIALOG="bsddialog"}
+: ${BSDINSTALL_ARGS=}
+
 ############################################################ GLOBALS
 
 #
@@ -40,7 +43,6 @@ f_include $BSDCFG_SHARE/dialog.subr
 # script.
 #
 user_env_vars="BSDINSTALL_DISTSITE DISTRIBUTIONS WORKAROUND_GPTACTIVE WORKAROUND_LENOVO ZFSBOOT_PARTITION_SCHEME"
-: ${DIALOG="bsddialog"}
 
 #
 # Strings that should be moved to an i18n file and loaded with f_include_lang()
@@ -84,7 +86,7 @@ error()
 	local prompt="${1:+$1\n\n}$msg_an_installation_step_has_been_aborted"
 	local hline="$hline_arrows_tab_space_enter"
 
-	[ -f "$PATH_FSTAB" ] && bsdinstall umount
+	[ -f "$PATH_FSTAB" ] && bsdinstall $BSDINSTALL_ARGS umount
 
 	local height width
 	f_dialog_buttonbox_size height width \
@@ -193,10 +195,10 @@ fi
 [ -f /usr/libexec/bsdinstall/local.pre-everything ] && f_dprintf "Running local.pre-everything" && sh /usr/libexec/bsdinstall/local.pre-everything "$BSDINSTALL_CHROOT"
 
 trap true SIGINT	# This section is optional
-[ -z "$BSDINSTALL_SKIP_KEYMAP" ] && bsdinstall keymap
+[ -z "$BSDINSTALL_SKIP_KEYMAP" ] && bsdinstall $BSDINSTALL_ARGS keymap
 
 trap error SIGINT	# Catch cntrl-C here
-if [ -z "$BSDINSTALL_SKIP_HOSTNAME" ]; then bsdinstall hostname || error "Set hostname failed"; fi
+if [ -z "$BSDINSTALL_SKIP_HOSTNAME" ]; then bsdinstall $BSDINSTALL_ARGS hostname || error "Set hostname failed"; fi
 
 if [ -f /usr/freebsd-packages/repos/FreeBSD-base-offline.conf ]; then
 	HAVE_BASE_PACKAGES=yes
@@ -226,13 +228,13 @@ if [ "$PKGBASE" == yes ]; then
 		if [ $? -eq 1 ]; then
 			export BSDINSTALL_PKG_REPOS_DIR=/usr/freebsd-packages/repos/
 		else
-			bsdinstall netconfig || error
+			bsdinstall $BSDINSTALL_ARGS netconfig || error
 			NETCONFIG_DONE=yes
 		fi
 	else
 		$DIALOG --backtitle "$OSNAME Installer" --title "Network Installation" \
 		    --msgbox "No base system packages are included in this installation media. The next few screens will allow you to configure networking." 0 0
-		bsdinstall netconfig || error
+		bsdinstall $BSDINSTALL_ARGS netconfig || error
 		NETCONFIG_DONE=yes
 	fi
 else
@@ -264,9 +266,15 @@ else
 
 	if [ -n "$FETCH_DISTRIBUTIONS" -a -n "$BSDINSTALL_CONFIGCURRENT" ]; then
 		$DIALOG --backtitle "$OSNAME Installer" --title "Network Installation" --msgbox "Some installation files were not found on the boot volume. The next few screens will allow you to configure networking so that they can be downloaded from the Internet." 0 0
-		bsdinstall netconfig || error
+		bsdinstall $BSDINSTALL_ARGS netconfig || error
 		NETCONFIG_DONE=yes
 	fi
+=======
+if [ -n "$FETCH_DISTRIBUTIONS" -a -n "$BSDINSTALL_CONFIGCURRENT" ]; then
+	$DIALOG --backtitle "$OSNAME Installer" --title "Network Installation" --msgbox "Some installation files were not found on the boot volume. The next few screens will allow you to configure networking so that they can be downloaded from the Internet." 0 0
+	bsdinstall $BSDINSTALL_ARGS netconfig || error
+	NETCONFIG_DONE=yes
+>>>>>>> e1056a4f5ee5 (bsdinstall: add support for graphical mode)
 fi
 
 rm -f $PATH_FSTAB
@@ -399,27 +407,27 @@ fi
 
 case "$PARTMODE" in
 "$msg_auto_zfs")	# ZFS
-	bsdinstall zfsboot || error "ZFS setup failed"
-	bsdinstall mount || error "Failed to mount filesystem"
+	bsdinstall $BSDINSTALL_ARGS zfsboot || error "ZFS setup failed"
+	bsdinstall $BSDINSTALL_ARGS mount || error "Failed to mount filesystem"
 	;;
 "$msg_auto_ufs")	# Guided UFS
-	bsdinstall autopart || error "Partitioning error"
-	bsdinstall mount || error "Failed to mount filesystem"
+	bsdinstall $BSDINSTALL_ARGS autopart || error "Partitioning error"
+	bsdinstall $BSDINSTALL_ARGS mount || error "Failed to mount filesystem"
 	;;
 "$msg_shell")		# Shell
 	clear
 	echo "Use this shell to set up partitions for the new system. When finished, mount the system at $BSDINSTALL_CHROOT and place an fstab file for the new system at $PATH_FSTAB. Then type 'exit'. You can also enter the partition editor at any time by entering 'bsdinstall partedit'."
 	sh 2>&1
-	bsdinstall mount_aux || error "Failed to mount auxiliary filesystems"
+	bsdinstall $BSDINSTALL_ARGS mount_aux || error "Failed to mount auxiliary filesystems"
 	;;
 "$msg_manual")		# Manual
 	if f_isset debugFile; then
 		# Give partedit the path to our logfile so it can append
-		BSDINSTALL_LOG="${debugFile#+}" bsdinstall partedit || error "Partitioning error"
+		BSDINSTALL_LOG="${debugFile#+}" bsdinstall $BSDINSTALL_ARGS partedit || error "Partitioning error"
 	else
-		bsdinstall partedit || error "Partitioning error"
+		bsdinstall $BSDINSTALL_ARGS partedit || error "Partitioning error"
 	fi
-	bsdinstall mount || error "Failed to mount filesystem"
+	bsdinstall $BSDINSTALL_ARGS mount || error "Failed to mount filesystem"
 	;;
 *)
 	error "Unknown partitioning mode"
@@ -429,7 +437,7 @@ esac
 [ -f /usr/libexec/bsdinstall/local.pre-fetch ] && f_dprintf "Running local.pre-fetch" && sh /usr/libexec/bsdinstall/local.pre-fetch "$BSDINSTALL_CHROOT"
 
 if [ "$PKGBASE" == yes ]; then
-	bsdinstall pkgbase || error "Installation of base system packages failed"
+	bsdinstall $BSDINSTALL_ARGS pkgbase || error "Installation of base system packages failed"
 else
 	if [ -n "$FETCH_DISTRIBUTIONS" ]; then
 		exec 5>&1
@@ -439,36 +447,36 @@ else
 
 		[ $FETCH_RESULT -ne 0 ] && error "Could not fetch remote distributions"
 	fi
-	bsdinstall checksum || error "Distribution checksum failed"
-	bsdinstall distextract || error "Distribution extract failed"
+	bsdinstall $BSDINSTALL_ARGS checksum || error "Distribution checksum failed"
+	bsdinstall $BSDINSTALL_ARGS distextract || error "Distribution extract failed"
 fi
 
 # Set up boot loader
-bsdinstall bootconfig || error "Failed to configure bootloader"
+bsdinstall $BSDINSTALL_ARGS bootconfig || error "Failed to configure bootloader"
 
 [ -f /usr/libexec/bsdinstall/local.pre-configure ] && f_dprintf "Running local.pre-configure" && sh /usr/libexec/bsdinstall/local.pre-configure "$BSDINSTALL_CHROOT"
 
-bsdinstall rootpass || error "Could not set root password"
+bsdinstall $BSDINSTALL_ARGS rootpass || error "Could not set root password"
 
 trap true SIGINT	# This section is optional
 if [ "$NETCONFIG_DONE" != yes ]; then
-	bsdinstall netconfig	# Don't check for errors -- the user may cancel
+	bsdinstall $BSDINSTALL_ARGS netconfig	# Don't check for errors -- the user may cancel
 fi
-[ -z "$BSDINSTALL_SKIP_TIME" ] && bsdinstall time
-[ -z "$BSDINSTALL_SKIP_SERVICES" ] && bsdinstall services
-[ -z "$BSDINSTALL_SKIP_HARDENING" ] && bsdinstall hardening
-[ -z "$BSDINSTALL_SKIP_FIRMWARE" ] && bsdinstall firmware
+[ -z "$BSDINSTALL_SKIP_TIME" ] && bsdinstall $BSDINSTALL_ARGS time
+[ -z "$BSDINSTALL_SKIP_SERVICES" ] && bsdinstall $BSDINSTALL_ARGS services
+[ -z "$BSDINSTALL_SKIP_HARDENING" ] && bsdinstall $BSDINSTALL_ARGS hardening
+[ -z "$BSDINSTALL_SKIP_FIRMWARE" ] && bsdinstall $BSDINSTALL_ARGS firmware
 
 [ -z "$BSDINSTALL_SKIP_USERS" ] && $DIALOG --backtitle "$OSNAME Installer" \
 	--title "Add User Accounts" --yesno \
     "Would you like to add users to the installed system now?" 0 0 && \
-    bsdinstall adduser
+    bsdinstall $BSDINSTALL_ARGS adduser
 
 # Allow user to change his mind
-[ -z "$BSDINSTALL_SKIP_FINALCONFIG" ] && bsdinstall finalconfig
+[ -z "$BSDINSTALL_SKIP_FINALCONFIG" ] && bsdinstall $BSDINSTALL_ARGS finalconfig
 
 trap error SIGINT	# SIGINT is bad again
-bsdinstall config  || error "Failed to save config"
+bsdinstall $BSDINSTALL_ARGS config  || error "Failed to save config"
 
 if [ ! -z "$BSDINSTALL_FETCHDEST" ]; then
 	rm -rf "$BSDINSTALL_FETCHDEST"
@@ -488,8 +496,8 @@ if [ -z "$BSDINSTALL_SKIP_MANUAL" ]; then
 	fi
 fi
 
-bsdinstall entropy
-bsdinstall umount
+bsdinstall $BSDINSTALL_ARGS entropy
+bsdinstall $BSDINSTALL_ARGS umount
 
 f_dprintf "Installation Completed at %s" "$( date )"
 
diff --git a/usr.sbin/bsdinstall/scripts/jail b/usr.sbin/bsdinstall/scripts/jail
--- a/usr.sbin/bsdinstall/scripts/jail
+++ b/usr.sbin/bsdinstall/scripts/jail
@@ -40,6 +40,7 @@ BSDCFG_SHARE="/usr/share/bsdconfig"
 #
 user_env_vars="BSDINSTALL_DISTSITE DISTRIBUTIONS"
 : ${DIALOG="bsddialog"}
+: ${BSDINSTALL_ARGS=}
 
 ############################################################ FUNCTIONS
 
@@ -116,11 +117,11 @@ distbase() {
 	fi
 
 	if [ ! -z "$FETCH_DISTRIBUTIONS" ]; then
-		bsdinstall distfetch || error "Failed to fetch distribution"
+		bsdinstall $BSDINSTALL_ARGS distfetch || error "Failed to fetch distribution"
 	fi
 
-	bsdinstall checksum || error "Distribution checksum failed"
-	bsdinstall distextract || error "Distribution extract failed"
+	bsdinstall $BSDINSTALL_ARGS checksum || error "Distribution checksum failed"
+	bsdinstall $BSDINSTALL_ARGS distextract || error "Distribution extract failed"
 }
 
 # environment_restore
@@ -184,29 +185,29 @@ if [ ! "$nonInteractive" == "YES" ]; then
 fi
 
 if [ "$PKGBASE" == yes ]; then
-	bsdinstall pkgbase --jail || error "Installation of base system packages failed"
+	bsdinstall $BSDINSTALL_ARGS pkgbase --jail || error "Installation of base system packages failed"
 else
 	distbase
 fi
 
 if [ ! "$nonInteractive" == "YES" ]
 then
-    bsdinstall rootpass || error "Could not set root password"
+    bsdinstall $BSDINSTALL_ARGS rootpass || error "Could not set root password"
 fi
 
 trap true SIGINT	# This section is optional
 
 if [ ! "$nonInteractive" == "YES" ]
 then
-bsdinstall services
+bsdinstall $BSDINSTALL_ARGS services
 
     $DIALOG --backtitle "$OSNAME Installer" --title "Add User Accounts" --yesno \
         "Would you like to add users to the installed system now?" 0 0 && \
-        bsdinstall adduser
+        bsdinstall $BSDINSTALL_ARGS adduser
 fi
 
 trap error SIGINT	# SIGINT is bad again
-bsdinstall config  || error "Failed to save config"
+bsdinstall $BSDINSTALL_ARGS config  || error "Failed to save config"
 cp /etc/resolv.conf $1/etc
 cp -P /etc/localtime $1/etc
 cp /var/db/zoneinfo $1/var/db
@@ -222,7 +223,7 @@ if [ -f $TMPDIR/bsdinstall-installscript-setup ]; then
 	rm $BSDINSTALL_CHROOT/tmp/installscript
 fi
 
-bsdinstall entropy
+bsdinstall $BSDINSTALL_ARGS entropy
 
 f_dprintf "Installation Completed at %s" "$(date)"
 exit $SUCCESS
