bsdinstall: use a regular gauge for checksum validation

diff --git a/usr.sbin/bsdinstall/scripts/checksum b/usr.sbin/bsdinstall/scripts/checksum
--- a/usr.sbin/bsdinstall/scripts/checksum
+++ b/usr.sbin/bsdinstall/scripts/checksum
@@ -1,6 +1,7 @@
 #!/bin/sh
 #-
 # Copyright (c) 2011 Nathan Whitehorn
+# Copyright (c) 2024 The FreeBSD Foundation
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -30,60 +31,67 @@ test -f $BSDINSTALL_DISTDIR/MANIFEST || exit 0
 BSDCFG_SHARE="/usr/share/bsdconfig"
 . $BSDCFG_SHARE/common.subr || exit 1
 
+: ${TMPDIR=/tmp}
 : ${BSDDIALOG=bsddialog}
+: ${BSDINSTALL_TMPCHECKSUM="${TMPDIR}/bsdinstall_checksum"}
 
-dist_to_statusvar()
+checksum()
 {
-	printf 'status_'
-	echo "$1" | sed 's/_/__/g;s/\./_dot_/g;s/-/_dash_/g'
+	percentage=0
+	for dist in $DISTRIBUTIONS; do
+		echo "XXX"
+		echo "$percentage"
+		echo
+		echo "$dist: validating checksum..."
+
+		CK=`sha256 -q $BSDINSTALL_DISTDIR/$dist`
+		awk -v checksum=$CK -v dist=$dist -v found=0 '{
+			if (dist == $1) {
+				found = 1
+				if (checksum == $2)
+					exit(0)
+				else
+					exit(2)
+			}
+		} END {if (!found) exit(1);}' $BSDINSTALL_DISTDIR/MANIFEST
+
+		CK_VALID=$?
+		if [ $CK_VALID -le 1 ]; then
+			percentage=$((percentage + 100/$(echo $DISTRIBUTIONS | wc -w) ))
+			echo "XXX"
+			echo "$percentage"
+			echo
+			if [ $CK_VALID -eq 0 ]; then
+				echo "$dist: checksum validated"
+			else
+				echo "$dist: checksum not found"
+			fi
+		else
+			case $(/bin/freebsd-version -u) in
+			*-ALPHA*|*-CURRENT|*-STABLE|*-PRERELEASE)
+				echo "EOF"
+				echo "The checksum for $dist does not match. It may have become corrupted, or it may be from a newer version of $OSNAME. Please check for a newer snapshot." > "$BSDINSTALL_TMPCHECKSUM"
+				;;
+			*)
+				echo "EOF"
+				echo "The checksum for $dist does not match. It may have become corrupted, and should be redownloaded." > "$BSDINSTALL_TMPCHECKSUM"
+				;;
+			esac
+			exit 1
+		fi
+	done
+	echo "EOF"
 }
 
-percentage=0
-for dist in $DISTRIBUTIONS; do
-	statusvar=$(dist_to_statusvar $dist)
-	eval "$statusvar=-8"
+checksum | $BSDDIALOG --backtitle "$OSNAME Installer" \
+		 --title "Checksum Verification" \
+		 --gauge "\nVerifying checksums of selected distributions.\n" \
+		 0 0 0
 
-	items=""
-	for i in $DISTRIBUTIONS; do
-		items="$items $i `eval echo \\\${$(dist_to_statusvar $i):--11}`"
-	done
-	$BSDDIALOG --backtitle "$OSNAME Installer" --title "Checksum Verification" \
-	    --mixedgauge "\nVerifying checksums of selected distributions.\n" \
-	    0 0 $percentage  -- $items
-
-	CK=`sha256 -q $BSDINSTALL_DISTDIR/$dist`
-	awk -v checksum=$CK -v dist=$dist -v found=0 '{
-		if (dist == $1) {
-			found = 1
-			if (checksum == $2)
-				exit(0)
-			else
-				exit(2)
-		}
-	} END {if (!found) exit(1);}' $BSDINSTALL_DISTDIR/MANIFEST
-
-	CK_VALID=$?
-	if [ $CK_VALID -le 1 ]; then
-		if [ $CK_VALID -eq 0 ]; then
-			eval "$statusvar=-3"
-		else
-			eval "$statusvar=-7"
-		fi
-		percentage=$(echo $percentage + 100/`echo $DISTRIBUTIONS | wc -w` | bc)
-	else
-		eval "$statusvar=-2"
-		case $(/bin/freebsd-version -u) in
-		*-ALPHA*|*-CURRENT|*-STABLE|*-PRERELEASE)
-			$BSDDIALOG --backtitle "$OSNAME Installer" --title "Error" \
-			    --msgbox "The checksum for $dist does not match. It may have become corrupted, or it may be from a newer version of $OSNAME. Please check for a newer snapshot." 0 0
-			;;
-		*)
-			$BSDDIALOG --backtitle "$OSNAME Installer" --title "Error" \
-			    --msgbox "The checksum for $dist does not match. It may have become corrupted, and should be redownloaded." 0 0
-			;;
-		esac
-		exit 1
-	fi
-done
-
+ if [ -f "$BSDINSTALL_TMPCHECKSUM" ]; then
+	$BSDDIALOG --backtitle "$OSNAME Installer" --title "Error" \
+	    --msgbox "$(cat "$BSDINSTALL_TMPCHECKSUM")" 0 0
+	rm -f "$BSDINSTALL_TMPCHECKSUM"
+	exit 1
+fi
 exit 0
