bsdinstall: handle command-line options in targets
This adds a usage screen to bsdinstall(8).

This will allow adding support for graphical mode with "-X", as is
already the case with bsdconfig(8).

The changes in the targets are necessary in this regard, as processing
the "-X" flag in bsdconfig's dialog.subr will expect it as a parameter
there.

Sponsored by:	The FreeBSD Foundation

diff --git a/usr.sbin/bsdinstall/bsdinstall b/usr.sbin/bsdinstall/bsdinstall
--- a/usr.sbin/bsdinstall/bsdinstall
+++ b/usr.sbin/bsdinstall/bsdinstall
@@ -34,6 +34,21 @@
 export DEBUG_SELF_INITIALIZE=
 export DEBUG_INITIALIZE_FILE=
 
+# When common.subr is included, it automatically scans "$@" for `-d' and/or
+# `-D file' arguments to conditionally enable debugging. Similarly, when
+# dialog.subr is included, it automatically scans "$@" for `-X' and/or `-S'.
+# To prevent this scanning from becoming confused by extra options, define
+# any/all extra arguments to use in the optstring to getopts when scanning
+# for dedicated options such as those described.
+#
+# NOTE: This needs to be declared before including `common.subr'.
+# NOTE: You really only need to list flags that require an argument as unknown
+#       flags are silently accepted unless they take an argument (in which case
+#       the following argument will terminate option processing unless it looks
+#       like a flag).
+#
+GETOPTS_EXTRA=
+
 BSDCFG_SHARE="/usr/share/bsdconfig"
 . $BSDCFG_SHARE/common.subr || exit 1
 
@@ -49,13 +64,28 @@ BSDCFG_SHARE="/usr/share/bsdconfig"
 
 export debugFile="${debugFile-${BSDINSTALL_LOG-${TMPDIR}/bsdinstall_log}}"
 
+############################################################ USAGE
+
+usage()
+{
+	echo "Usage: bsdinstall [-$GETOPTS_EXTRA$GETOPTS_STDARGS][target][...]" 1>&2
+	echo "  -d	Enable debugging output" 1>&2
+	echo "  -D	Save debugging output to a file" 1>&2
+	return 1
+}
+
 ############################################################ MAIN
 
 #
 # Process command-line arguments
 #
-while getopts $GETOPTS_STDARGS ignored; do
-	: just skipping known flags
+while getopts "$GETOPTS_EXTRA$GETOPTS_STDARGS" name; do
+	case "$name" in
+		'?')
+			usage
+			exit $?
+			;;
+	esac
 done
 shift $(( $OPTIND - 1 ))
 
